### Add User
POST {{host}}/add_user/
Content-Type: application/json

{
  "username": "user3"
}

### Add Transaction
POST {{host}}/add_transaction/2
Content-Type: application/json

{
  "amount": 11.1,
  "type": "deposit"
}


### Get user
GET {{host}}/get_user/1
Content-Type: application/json

### Get all user
GET {{host}}/get_all_users
Content-Type: application/json
